/**
 * Source-generation for `ap-sdk init` — stamps out a working starter plugin
 * wired to the public SDK entrypoint.
 *
 * The generated file validates as-is and demonstrates instructions, one skill,
 * and one command so new authors edit a real plugin rather than a blank stub.
 */

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** Validate a plugin id, returning an error string or null. */
export function validatePluginId(id: string): string | null {
  if (!id) return "a plugin id is required (e.g. `ap-sdk init my-plugin`)";
  if (!KEBAB.test(id)) {
    return `plugin id "${id}" must be kebab-case (lowercase letters, digits, single hyphens)`;
  }
  return null;
}

/** Render the TypeScript source for a starter plugin. */
export function pluginTemplate(id: string, pkg = "@jalco/ap-sdk"): string {
  return `// Generated by \`ap-sdk init ${id}\`.
// See https://ap-sdk.dev/docs/quickstart for the full walkthrough.
import { definePlugin, defineSkill, defineCommand } from "${pkg}";

export default definePlugin({
  id: "${id}",
  description: "Helpers for working with git in a repo.",
  instructions: "## Git\\n- Branch off main; never commit to it directly.",
  skills: [
    defineSkill({
      name: "diff-review",
      description:
        "Summarize and risk-flag uncommitted changes. Use when the user asks what changed.",
      instructions: "Run \`git diff HEAD\` and summarize the changes in 2-4 bullets.",
    }),
  ],
  commands: [
    defineCommand({
      name: "commit",
      description: "Write a conventional commit for the staged changes.",
      body: "Write a Conventional Commit message for the staged diff. Args: $ARGUMENTS",
    }),
  ],
});
`;
}

/** Files generated by the SDK should not be committed by default. */
export function gitignoreSnippet(): string {
  return ".aps-out/\n";
}
