/**
 * Source-generation for `ap-sdk add-harness` — stamps out a typed
 * {@link Harness} stub wired to the public `/harness` authoring entrypoint.
 *
 * The generated file compiles as-is and produces real (if minimal) artifacts —
 * a SKILL.md-based starter that supports instructions, skills, and commands —
 * so the author edits a working harness rather than filling in a blank.
 */

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** Turn a kebab id into a default display name, e.g. `gemini-cli` → `Gemini Cli`. */
export function deriveDisplayName(id: string): string {
  return id
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Validate a harness id, returning an error string or null. */
export function validateHarnessId(id: string): string | null {
  if (!id) return "a harness id is required (e.g. `ap-sdk add-harness gemini`)";
  if (!KEBAB.test(id)) {
    return `harness id "${id}" must be kebab-case (lowercase letters, digits, single hyphens)`;
  }
  return null;
}

/**
 * Render the TypeScript source for a new harness module.
 *
 * @param id          kebab-case harness id (becomes `Harness.id` and the install dir `.<id>/`)
 * @param displayName human-readable label for CLI output
 * @param pkg         the SDK package name to import the toolkit from
 */
export function harnessTemplate(
  id: string,
  displayName: string,
  pkg = "@jalco/ap-sdk",
): string {
  const constName = id.replace(/-([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
  return `import { homedir } from "node:os";
import { join } from "node:path";
import {
  defineHarness,
  registerHarness,
  emitSkillDir,
  emitCommandFile,
  emitContextFile,
  compact,
  type Harness,
  type InstallScope,
} from "${pkg}/harness";

/**
 * ${displayName} harness.
 *
 * Generated by \`ap-sdk add-harness ${id}\`. This is a working SKILL.md-based
 * starter: it supports instructions, skills, and commands. Flip \`supports\` flags
 * to true and translate the corresponding features in \`emit\` as you implement
 * them — anything left \`false\` degrades to a structured build warning, never a
 * broken artifact.
 */
export const ${constName}: Harness = defineHarness({
  specificationVersion: "v1",
  id: "${id}",
  displayName: "${displayName}",

  // TODO: declare which portable features ${displayName} can represent natively.
  supports: {
    instructions: true,
    skills: true,
    commands: true,
    subagents: false,
    hooks: false,
    mcpServers: false,
    tools: false,
  },

  // The native always-on instruction file. TODO: set to this harness's real one.
  contextFileName: "AGENTS.md",

  emit(plugin) {
    // \`plugin\` is already projected to the features above — a pure translator.
    const files = [];

    if (plugin.instructions?.trim()) {
      files.push(
        emitContextFile(plugin.id, plugin.instructions, this.contextFileName),
      );
    }

    for (const skill of plugin.skills ?? []) {
      // TODO: emit only the frontmatter fields ${displayName} actually recognizes.
      const frontmatter = compact({
        name: skill.name,
        description: skill.description,
      });
      files.push(...emitSkillDir(skill, frontmatter, "skills"));
    }

    for (const command of plugin.commands ?? []) {
      const frontmatter = compact({ description: command.description });
      files.push(
        emitCommandFile(command.name, frontmatter, command.body, "commands"),
      );
    }

    return files;
  },

  // --- install paths -------------------------------------------------------
  // TODO: point these at ${displayName}'s real project/global directories.

  skillInstallDir(scope: InstallScope, name: string) {
    const root =
      scope === "global"
        ? join(homedir(), ".${id}", "skills")
        : join(".${id}", "skills");
    return join(root, name);
  },

  commandInstallPath(scope: InstallScope, name: string) {
    const root =
      scope === "global"
        ? join(homedir(), ".${id}", "commands")
        : join(".${id}", "commands");
    return join(root, name + ".md");
  },

  contextInstallPath(scope: InstallScope) {
    return scope === "global"
      ? join(homedir(), ".${id}", this.contextFileName)
      : this.contextFileName;
  },

  // --- unsupported-by-default features ------------------------------------
  // Return null so \`install\` reports a clean skip instead of writing a broken file.

  mcpInstall() {
    return null;
  },
  mcpInstallNote: "${displayName} MCP install is not implemented yet.",

  subagentInstallPath() {
    return null;
  },
  subagentNote: "${displayName} has no subagent support yet.",

  buildHookConfig() {
    return null;
  },
  hookInstall() {
    return null;
  },
  hookInstallNote: "${displayName} hooks are not implemented yet.",
});

// Register on import so \`build\`/\`install\`/the CLI pick it up. Import this file
// (e.g. from your plugin definition) before building.
registerHarness(${constName});
`;
}
