import type { McpServer } from "../types.js";

/**
 * Codegen for the shared tool runtime. A `defineTool` handler is real code, so
 * the SDK can't emit the logic — but it emits the thin per-harness glue (all
 * TypeScript) that imports the plugin's tools module and registers it via the
 * right runtime adapter. This is how one handler reaches every harness.
 *
 * The build copies the author's tools module into each harness output as
 * `tools.ts` (see `copyToolsModule` in the CLI / `installTools`), so the `./tools`
 * import below always resolves — no manual copy step, no dangling reference.
 */

/** The runtime package the generated glue imports from. */
const RUNTIME = "agent-plugin-sdk/runtime";

/** The MCP stdio server entry (TypeScript) for Claude/Codex — run via `tsx`. */
export function mcpServerEntry(pluginId: string): string {
  return (
    `// Generated by agent-plugin-sdk — runs this plugin's tools as an MCP server.\n` +
    `import tools from "../tools";\n` +
    `import { runMcpStdio } from ${JSON.stringify(RUNTIME)};\n\n` +
    `runMcpStdio(tools, { name: ${JSON.stringify(pluginId)} });\n`
  );
}

/** The Pi extension entry (registers tools via pi.registerTool). */
export function piExtensionEntry(): string {
  return (
    `// Generated by agent-plugin-sdk — registers this plugin's tools in Pi.\n` +
    `import tools from "./tools";\n` +
    `import { registerPiTools } from ${JSON.stringify(RUNTIME)};\n\n` +
    `export default function (pi: any) {\n` +
    `  registerPiTools(pi, tools);\n` +
    `}\n`
  );
}

/** The OpenCode plugin entry (exposes tools via the plugin tool map). */
export function openCodePluginEntry(): string {
  return (
    `// Generated by agent-plugin-sdk — exposes this plugin's tools in OpenCode.\n` +
    `import tools from "./tools";\n` +
    `import { createOpenCodePlugin } from ${JSON.stringify(RUNTIME)};\n\n` +
    `export const plugin = createOpenCodePlugin(tools);\n`
  );
}

/**
 * The MCP server entry, as a virtual `McpServer` so it flows through the same
 * `.mcp.json` generation as user-declared MCP servers. The server is TypeScript,
 * so it is launched with `tsx` (via `npx`, which resolves the project's local
 * `tsx`). `rootVar` is the harness's plugin-root substitution
 * (Claude `${CLAUDE_PLUGIN_ROOT}`), or `"."`.
 */
export function toolServerMcp(rootVar: string): McpServer {
  return {
    command: "npx",
    args: ["tsx", `${rootVar}/mcp/server.ts`],
  };
}
