// Generated by `ap-sdk init my-plugin`.
// See https://ap-sdk.dev/docs/quickstart for the full walkthrough.
import { definePlugin, defineSkill, defineCommand } from "@jalco/ap-sdk";

export default definePlugin({
  id: "my-plugin",
  description: "Helpers for working with git in a repo.",
  instructions: "## Git\n- Branch off main; never commit to it directly.",
  skills: [
    defineSkill({
      name: "diff-review",
      description:
        "Summarize and risk-flag uncommitted changes. Use when the user asks what changed.",
      instructions: "Run `git diff HEAD` and summarize the changes in 2-4 bullets.",
    }),
  ],
  commands: [
    defineCommand({
      name: "commit",
      description: "Write a conventional commit for the staged changes.",
      body: "Write a Conventional Commit message for the staged diff. Args: $ARGUMENTS",
    }),
  ],
});
